[package]
name = "charlesevangeliojr/archon"
version = "0.1.0"
description = "Archon Laravel Application"
readme = "README.md"

[dependencies]
"php/php" = "^8.3"

[fs]
"/app" = "."

[[features]]
name = "php"

[env]
DOCUMENT_ROOT = "/app/public"
